-- MySQL Script generated by MySQL Workbench
-- 11/01/15 17:05:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema olxbaby
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `olxbaby` ;

-- -----------------------------------------------------
-- Schema olxbaby
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `olxbaby` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `olxbaby` ;

-- -----------------------------------------------------
-- Table `olxbaby`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `olxbaby`.`user` ;

CREATE TABLE IF NOT EXISTS `olxbaby`.`user` (
  `iduser` INT NOT NULL COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `street` VARCHAR(45) NULL COMMENT '',
  `city` VARCHAR(45) NULL COMMENT '',
  `state` VARCHAR(45) NULL COMMENT '',
  `phone` VARCHAR(45) NULL COMMENT '',
  `image` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`iduser`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olxbaby`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `olxbaby`.`product` ;

CREATE TABLE IF NOT EXISTS `olxbaby`.`product` (
  `idproduct` INT NOT NULL COMMENT '',
  `producTitle` VARCHAR(45) NULL COMMENT '',
  `productPrice` VARCHAR(45) NULL COMMENT '',
  `productDescrpition` VARCHAR(45) NULL COMMENT '',
  `productImage` VARCHAR(45) NULL COMMENT '',
  `user_iduser` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idproduct`)  COMMENT '',
  INDEX `fk_product_user1_idx` (`user_iduser` ASC)  COMMENT '',
  CONSTRAINT `fk_product_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `olxbaby`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olxbaby`.`productCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `olxbaby`.`productCategory` ;

CREATE TABLE IF NOT EXISTS `olxbaby`.`productCategory` (
  `idProductCategory` INT NOT NULL COMMENT '',
  `carriageSeat` VARCHAR(45) NULL COMMENT '',
  `clothing` VARCHAR(45) NULL COMMENT '',
  `toys` VARCHAR(45) NULL COMMENT '',
  `cribs` VARCHAR(45) NULL COMMENT '',
  `others` VARCHAR(45) NULL COMMENT '',
  `product_idproduct` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idProductCategory`)  COMMENT '',
  INDEX `fk_productCategory_product1_idx` (`product_idproduct` ASC)  COMMENT '',
  CONSTRAINT `fk_productCategory_product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `olxbaby`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
